title = "Gregorio Vilardo - Porfolio"

[params.author]
name = "Gregorio Vilardo"
image = "img/profile.jpeg"
headline = "Computer Analyst, pursuing Bachelor of Computer Science (FaMAF)" 
bio = "Computer Analyst"
links = [
  { linkedin = "https://linkedin.com/in/gregovilardo" },
  { github = "https://github.com/gregovilardo" },
  { link = "https://media.licdn.com/dms/document/media/v2/D4D2DAQFVxL83moADNw/profile-treasury-document-pdf-analyzed/profile-treasury-document-pdf-analyzed/0/1735587519739?e=1736380800&v=beta&t=2O9pj9cJBWJLa1O1z_dMEqvdDasw0QGBOXs5VitvsPU" },
  { email = "mailto:gregovilardo@gmail.com" }
]
